apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor-project-proxy.fullname" . }}-conf
  labels:
    {{- include "harbor-project-proxy.labels" $ | nindent 4 }}
data:
  nginx.conf: |-
  {{- tpl (.Values.nginxConf | toString) $ | nindent 4 }}
