name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: "."
